services:
  app:
    container_name: setup-enviroment-app
    image: setup-enviroment-app
    tty: true
    volumes:
      - .:/app
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: app

  tests:
    container_name: setup-enviroment-test
    image: setup-enviroment-test
    env_file:
      - .env
    tty: true
    volumes:
      - .:/app
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: tests

