services:
  app:
    image: jacksonbicalho/setup-enviroment:01-bullseye-slin
    tty: true
    volumes:
      - .:/app

  shellspec:
    environment:
      - IMAGE=${IMAGE}
    image: "${IMAGE}"
    tty: true
    volumes:
      - .:/app

