version: '3'

services:
  app:
    container_name: debian-bookworm
    image: bookworm  
    privileged: true
    tty: true
    volumes:
      - .:/app
    build:
      context: ./
      dockerfile: ./Dockerfile


