services:
  app:
    container_name: jacksonbicalho-shellspec-kcov-app
    image: jacksonbicalho/setup-enviroment:debian-bookworm0.0.0
    tty: true
    volumes:
      - .:/app
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: app

  tests:
    container_name: jacksonbicalho-shellspec-kcov-tests
    image: jacksonbicalho/shellspec-kcov:debian-bookworm0.0.0
    # env_file:
    #   - .env
    tty: true
    volumes:
      - .:/app
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: tests

