version: '3'

services:
  app:
    container_name: etup-enviroment
    image: etup-enviroment  
    tty: true
    volumes:
      - .:/app
    build:
      context: ./
      dockerfile: ./Dockerfile

  


