services:
  app:
    container_name: setup-enviroment-app
    image: setup-enviroment-app
    tty: true
    volumes:
      - .:/app
    build:
      context: ./
      dockerfile: ./Dockerfile

  tests:
    container_name: setup-enviroment-test
    image: jacksonbicalho/shellspec-kcov:latest
    # env_file:
    #   - .env
    tty: true
    volumes:
      - .:/app

