#!/usr/bin/env bash

set -e

SRC_DIR=$(dirname "$0")
SCRIPTPATH="${SRC_DIR}/src"
SRC_RESOURCES="$( echo "$( cd "${SCRIPTPATH}" >/dev/null 2>&1 || exit ; pwd -P )" )"

CONSTANTS="${SRC_RESOURCES}/constants"
. "${CONSTANTS}"

if [ -d "$SRC_RESOURCES" ]; then
  extensions="*.sh"
  for file_name in ${SRC_RESOURCES}/${extensions}; do
    if [ -r "$file_name" ]; then
      . "${file_name}"
    fi
  done
  unset file_name
fi

action="main"

while getopts ':hf:' option; do
  case "$option" in
    h) help
       exit
       ;;
    f) action=$OPTARG
       ;;
    :) printf "missing argument for -%s\n" "$OPTARG" >&2
       help >&2
       exit 1
       ;;
   \?) printf "illegal option: -%s\n" "$OPTARG" >&2
       echo help >&2
       exit 1
       ;;
  esac
done

shift $((OPTIND - 1))


function main () {

  echo -e "$@"

  # #########################################
  # # Verica e/ou instala os pacotes essenciais para o funcionamento
  echo -e "Verificando pacotes essenciais..."
  essentials=$(join_by " " "${ESSENTIALS[@]}")
  check_dependencies "$essentials"

  figlet Seja bem vindo -w100

  if ! is_exist "${action}"; then
    help "A função ${action} não existe"
    exit;
  fi

  # #########################################
  # # call function from -f
  if [ "$action" != "main" ]; then
    ${action}
  fi

  init_config

  ssh_keygen

  check_git

  github_send_ssh_key

}


main "$@"
