#!/bin/bash

set -e

ROOT_DIR="$(cd "$(dirname "$0")/../" >/dev/null 2>&1 || exit ;  pwd -P)"
readonly CONFIG_PATH="$HOME/.config/setup-enviroment"
readonly APP_CONFIG_FILE="${CONFIG_PATH}/app.conf"
readonly LOG_PATH="${CONFIG_PATH}/log"
ESSENTIALS=("jq" "ca-certificates" "gnupg" "curl" "openssh-client")
ESSENTIALS+=("build-essential" "libgtk-3-dev" "intltool" "libgtk2.0-dev")
readonly ESSENTIALS+=("libglib2.0-dev" "libeditorconfig-dev" "figlet")
readonly GIT_HUB_NEW_TOKEN_URL="https://github.com/settings/tokens/new?description=Setup+enviroment&&scopes=admin:public_key"

readonly ALGORITHMS=("dsa" "ecdsa" "ecdsa-sk" "ed25519" "ed25519-sk" "rsa" "cancelar")
readonly SLEEP=0.5
readonly CONFIGS_INI=("full_name" "email")
readonly ROOT_DIR

export ROOT_DIR ESSENTIALS GIT_HUB_NEW_TOKEN_URL APP_CONFIG_FILE LOG_PATH
export ALGORITHMS SLEEP CONFIGS_INI CONFIG_PATH
