#!/bin/bash

set -e

readonly CONFIG_PATH="$HOME/.config/setup-enviroment"
readonly APP_CONFIG_FILE="${CONFIG_PATH}/.data"
readonly LOG_PATH="${CONFIG_PATH}/log"

readonly ESSENTIALS=("jq" "ca-certificates" "gnupg" "curl" "openssh-client" "build-essential"
  "libgtk-3-dev" "intltool" "libgtk2.0-dev" "libglib2.0-dev" "libeditorconfig-dev")

readonly REPOLIST_FILE="repolist.txt"

readonly GIT_HUB_NEW_TOKEN_URL="https://github.com/settings/tokens/new?description=\
  Setup+enviroment&&scopes=admin:public_key"

readonly ALGORITHMS=("dsa" "ecdsa" "ecdsa-sk" "ed25519" "ed25519-sk" "rsa" "cancelar")

readonly SLEEP=0.5

export ESSENTIALS REPOLIST_FILE GIT_HUB_NEW_TOKEN_URL \
  APP_CONFIG_FILE LOG_PATH ALGORITHMS SLEEP
