name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
      - name: Create dir
        run: |
          mkdir -p /app/logs
        run: |
          mkdir -p /app/coverage

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build docker images
      run: docker-compose build

    - name: Run tests
      run: docker-compose run shellspec --kcov
