name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
      working-directory: ./app

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run:  docker compose run --rm tests --
        working-directory: ./app
