name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Run test suite debian and variants
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: ./tests.sh
